Section "Files"
    FontPath    "/usr/share/fonts/misc"
    ModulePath  "/usr/lib/xorg/modules"
EndSection

Section "Module"
    Load "glx"
    Load "fbdevhw"
EndSection

Section "Device"
    Identifier  "fb0"
    Driver      "fbdev"
    Option      "fbdev"  "/dev/fb0"
EndSection

Section "Monitor"
    Identifier  "mon0"
    HorizSync   30-80
    VertRefresh 50-76
EndSection

Section "Screen"
    Identifier  "scr0"
    Device      "fb0"
    Monitor     "mon0"
    DefaultDepth 24
EndSection

Section "InputDevice"
    Identifier  "kbd0"
    Driver      "evdev"
    Option      "Device"    "/dev/input/event0"
    Option      "XkbModel"  "pc105"
    Option      "XkbLayout" "us"
EndSection

Section "InputDevice"
    Identifier  "mouse0"
    Driver      "evdev"
    Option      "Device"    "/dev/input/event1"
EndSection

Section "ServerLayout"
    Identifier  "layout0"
    Screen      "scr0"
    InputDevice "kbd0"   "CoreKeyboard"
    InputDevice "mouse0" "CorePointer"
EndSection

Section "ServerFlags"
    Option "AutoAddDevices" "false"
    Option "AutoEnableDevices" "false"
EndSection
